### ISSUE TITLE
TypeError: Cannot read property '_init' of undefined

### ISSUE THREAD

**Issue by IParthJoshi** [isaaclyman/vue-custom-element-ts-example#2]
@isaaclyman  this project worked perfectly fine untill I get to use the custom element tag outside of project or lets just say in index.html.
It gave me titled error, when I used the custom tags in index.html. 
when I was using custom-element with javascript app, I use to put the `<example-component>` in any outside .html file and mounted the build.js script to it, It worked as expected.
In typescript it has stopped working like that, and giving me below (same) error.
![vue-init](https://user-images.githubusercontent.com/28228669/35799654-6a3b9736-0a34-11e8-8ac4-055a84e00049.JPG)
Now to solve this error I had to do following in main.ts :
`Vue.customElement('example-component', new ExampleComponent().$options);`
This is a workaround which I founded in one of the issues, linked!
This way it works! But it also creates one problem, `beforeCreated()` and `created()` lifecycle hooks are called twice for the custom element passed. Which is logical when using `.$options`. Obviously that's not so cool.
Any solution to this ? on how we can just use :
 `Vue.customElement('example-component', ExampleComponent);` 
and eliminate lifecycle hooks being getting called twice ? 
After this I would like use only ExampleComponent as my entry point as custom element and Will be discarding MainComponent, so that I could load ExampleComponent directly in index.html by using tag ?

**Comment by isaaclyman** [comment]
I see. That doesn't look like a problem with the TypeScript declaration, though, it looks like a standard JavaScript error. Can you try switching over to JavaScript files and making sure you don't get the same bug? I only support the TypeScript declarations for vue-custom-element.

**Comment by IParthJoshi** [comment]
I made a new js app and tried but this works perfectly fine there. below are the screenshots for that.
My index.html :
![index](https://user-images.githubusercontent.com/28228669/35848432-2733e7d2-0aec-11e8-87ad-7e3658f21bef.JPG)
main.js :
![main](https://user-images.githubusercontent.com/28228669/35848456-3906547c-0aec-11e8-8a19-9ac8dda146fc.jpg)
example.vue :
![eg](https://user-images.githubusercontent.com/28228669/35848465-3f587aa8-0aec-11e8-9a42-574d36850252.JPG)
The same thing doesn't work if on typescript. Help me with this please!

**Comment by isaaclyman** [comment]
Can you please upload your example project to GitHub so I can try it for myself? I'd really appreciate it.
Sorry for the time delay. Looks like I'm asleep when you're awake.

**Comment by IParthJoshi** [comment]
@isaaclyman Yes, I am from India.  Below is your own `vue-custom-element-ts-example` project in which I have reproduced the error by eliminating MainComponent and giving ExampleComponent as my entry point.
Link : [https://github.com/IParthJoshi/vue-custom-element-ts](url)
waiting for your response...

**Comment by isaaclyman** [comment]
That repo does not have the same code that you screenshotted. "example-component.ts" is the problem and it will throw the same error, even if you change everything to regular JavaScript.

If you change "example-component.ts" to look like this:

```TypeScript
import Vue from "vue";
import component from "vue-class-component";

export default {
    data () {
        return { msg: "Vue in Typescript!" }
    }
}
```

Then it will work just fine. This demonstrates that the problem is *not* with the vue-custom-element TypeScript declaration.

**Comment by IParthJoshi** [comment]
@isaaclyman  Then can you suggest something. Because we need to use that `@component` decorator and write code as class component way. Not like the way you have shown, for following some typescript class type of code. This also means writing the code like typescript class component way wont work with `custom-element` unless you have a workaround like this 'new ExampleComponent().$options', which is bad form to do. Can you suggest a way out of this or could issue-ing this one on `vue-class-component` will help ?

**Comment by isaaclyman** [comment]
I think you'll find that this one is not an easy fix. vue-custom-element doesn't understand how to use `@component`-annotated components, karol doesn't know TypeScript, and I only support the TypeScript declaration file, not the actual functionality of vue-custom-element. If you write a fix for the problem, I expect karol will welcome a pull request to the original repository.

**Comment by IParthJoshi** [comment]
Okay thanks! Will sure do something about it.

**Comment by borishuseincehajic** [comment]
@IParthJoshi hey, I know this is an old thread but did you happen to find a solution to this one. Got the same problem.

**Comment by johnnyshankman** [comment]
I'd like to reopen this if it has not been fixed but I suppose i should open this in the vue-custom-element repo. I cannot use the most common decorator API `vue-property-decorator` with this tool and so my whole codebase would need refactoring to use it with this. Super disappointed by that :/ It's unable to translate the `VueComponent` class into a class object-style vue export.

```
export default {
  props: ...,
  data () : void {
    ....
  },
}
```

works but this does not

```
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class MyExport extends Vue {
  @Prop...
  ...
}
```

https://github.com/kaorun343/vue-property-decorator
